services:
  - type: web
    name: nexusqa-backend
    env: python
    branch: main
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn --app-dir . api:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DB_URL
        value: "postgresql://admin:pR6aFnyZm6nc1wlCheGVXvjJ5VZrLZQ6@dpg-d0d26gjuibrs73dra1tg-a.oregon-postgres.render.com:5432/contazoom?sslmode=require"
      - key: ML_CLIENT_ID
        value: "3597957782423859"
      - key: ML_CLIENT_SECRET
        value: "sZOG7DCPZzQhWbqSn4ii6UJx4upEzQMd"
      - key: BACKEND_URL
        value: "https://nexus-backend-0dzu.onrender.com"
      - key: FRONTEND_URL
        value: "https://nexus-dashboard-13ej.onrender.com"

  - type: web
    name: nexusqa-dashboard
    env: python
    branch: main
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.enableXsrfProtection false"
    envVars:
      - key: DB_URL
        value: "postgresql://admin:pR6aFnyZm6nc1wlCheGVXvjJ5VZrLZQ6@dpg-d0d26gjuibrs73dra1tg-a.oregon-postgres.render.com:5432/contazoom?sslmode=require"
      - key: BACKEND_URL
        value: "https://nexus-backend-0dzu.onrender.com"
      - key: ML_CLIENT_ID
        value: "3597957782423859"
      - key: FRONTEND_URL
        value: "https://nexus-dashboard-13ej.onrender.com"
      - key: WEB_PASSWORD
        value: "Giguisa*"
